version: '3'
services:
    cs-materials:
        env_file:
            - .env
        build:
            context: .
            args:
                SERVER_PORT: ${SERVER_PORT}
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
        volumes:
            - ..:/mnt/project/:ro
